### ISSUE TITLE
Blender import state is not working

### ISSUE THREAD

**Issue by rodrigo-cgi** [PrismPipeline/Prism#12]
**Describe the bug**
Import state is not working on Blender 2.8

**To Reproduce**
1. Export a simple blender scene using the State Manager
2. In another scene, open the state manager and import
3. Choose either make or not a reference
4. Error Message:
![image](https://user-images.githubusercontent.com/34991118/66731076-3f43c380-ee0a-11e9-8c4f-9810e44cc9df.png)

**Expected behavior**
Import the file

**Screenshots**
![image](https://user-images.githubusercontent.com/34991118/66731083-4d91df80-ee0a-11e9-8878-28857c301200.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.0

**Additional context**
nothing to add

**Comment by RichardFrangenberg** [comment]
That issue should be fixed in the latest development version. You can open the Prism Settings dialog and in the "miscellaneous" tab you can update to the latest Prism github version (currently v1.2.1.31)
