### ISSUE TITLE
Structure bug when creating asset entry in project browser

### ISSUE THREAD

**Issue by chrbir** [PrismPipeline/Prism#14]
Project browser shows folder structure in asset entry

![prism_bug](https://user-images.githubusercontent.com/6834867/75833052-1e2f3f80-5db8-11ea-99d5-a6e3eef82637.png)

Prism version: 1.2.1.57
OS: Windows 10

**Comment by RichardFrangenberg** [comment]
That should be fixed now in v1.2.1.58
The asset which you already created will still have this problem, because it has incorrect subfolders. You can rename the subfolders manually or simply create a new asset.
